### ISSUE TITLE
hydra_ros_node

### ISSUE THREAD

**Issue by hibaQaysi** [MIT-SPARK/Hydra-ROS#3] opened 2024-02-22 11:07 UTC
Hi,

I am trying to run roslaunch hydra_ros uhumans2.launch, but I am getting an error that the hydra_ros_node does not exist within the package src (along with bunch of other nodes). I have followed the installations and building steps and sourced the ws and all.
can you please check why is that?

<img width="1044" alt="error" src="https://github.com/MIT-SPARK/Hydra-ROS/assets/156114448/059b35be-02a3-4c2a-8f8f-f00793e2dc72">

**Comment by nathanhhughes** [comment] 2024-07-09 14:58
Closing as duplicate of transferred issue

**Closed by nathanhhughes** 2024-07-09 14:58 UTC
Labels: question
